SELECT
	HU.UM,
	HU.CAMP,
	HU.DTH_ENTRD_EQPMT,
	--MAX(HU.POS) AS COMPMAX,
	ROUND(AVG(HU.DEV), 2) AS DEV_MED_CAMB_SAIDA,
	MAX(HU.DEV) AS DEV_MAX_CAMB_SAIDA,
	MIN(HU.DEV) AS DEV_MIN_CAMB_SAIDA
FROM
	(
	SELECT
		VP.COD_IDENT_UNMET AS UM,
		T2.DTH_ENTRD_EQPMT,
		DPUV.COD_CAMP_LTQ AS CAMP,
		VP.COD_TIPO_MEDID AS TIPO,
		VP.DEV_MM_UNMET AS DEV,
		VP.POS_LONGL_UNMET AS POS
		
	FROM
		ACECPGER_LTQ.PROC_MEDID_LAR_PERFIL VP
	INNER JOIN
        ACECPGER_LTQ.HISTORICOS_UM T2
    ON
		VP.COD_IDENT_UNMET = T2.COD_IDENT_UNMET
		
	INNER JOIN ACECPGER_LTQ.UNIDADES_METALICAS DPUV
	ON DPUV.COD_IDENT_UNMET = T2.COD_IDENT_UNMET
	
	WHERE
		T2.DTH_ENTRD_EQPMT >= TO_TIMESTAMP('2020-01-01 00:03:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3')
		AND COD_EQPMT_PRODC = 'LTQ'
    ) HU
WHERE
    HU.POS > 500
	AND HU.POS < 45000
GROUP BY
	HU.UM,
	HU.DTH_ENTRD_EQPMT,
	HU.CAMP
ORDER BY
	HU.UM ASC