SELECT
	T1.COD_IDENT_UNMET,
	T1.ESP_MM_UNMET,
	T1.LAR_MM_UNMET,
	DPUV.COD_IDENT_FMACO,
	--DPUV.COD_PRODC_SAIDA,
	DPUV.DTH_FIM_SAIDA 
FROM
	ACECPGER_LTQ.HISTORICOS_UM T1
INNER JOIN ACECPGER_LTQ.DADOS_PRODUCAO_UMS_VIEW DPUV ON
	T1.COD_IDENT_UNMET = DPUV.COD_IDENT_UNMET
WHERE
	DPUV.COD_IDENT_FMACO ='3XX' -- SUBSTITUA PARA ALTERAR A FAMILIA
	AND
	--DPUV.COD_IDENT_UNMET ='361073J01'    -- PARA TESTES
	--AND 
	DPUV.COD_PRODC_SAIDA ='LTQ'
	AND 
T1.DTH_FIM_PROCE >= TO_TIMESTAMP('2023-06-01 02:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3') -- Data e hora inicial desejada
	
	AND T1.DTH_FIM_PROCE <= TO_TIMESTAMP('2023-06-02 23:59:59.999', 'YYYY-MM-DD HH24:MI:SS.FF3') -- Data e hora final desejada 
	
GROUP BY
	T1.COD_IDENT_UNMET,
	T1.ESP_MM_UNMET,
	T1.LAR_MM_UNMET,
	DPUV.COD_IDENT_FMACO ,
	DPUV.DTH_FIM_SAIDA ,
	DPUV.COD_PRODC_SAIDA
 ORDER BY 
 T1.COD_IDENT_UNMET