SELECT
    COD_IDENT_UNMET AS UM,
    DTH_PROCESS_MED,
    MIN(ESP_MM_RX) AS MIN_ESP_MM,
    ROUND(AVG(ESP_MM_RX), 2) AS MED_ESP_MM,
    MAX(ESP_MM_RX) AS MAX_ESP_MM
    

FROM ACECPGER_RX.PROC_DADOS_METRO_RX 
WHERE
--COD_IDENT_UNMET = '707495H04' -- Para testes
DTH_PROCESS_MED >= TO_TIMESTAMP('2023-01-01 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3') -- Inicio
AND COMP_MM_TIRA >= 10 --Posicao inicial defeito
AND COMP_MM_TIRA <= 40 --Posicao final defeito
GROUP BY
  COD_IDENT_UNMET ,
    DTH_PROCESS_MED
ORDER BY
    UM ASC
